name: kmp_shared_sdk_flutter
description: Flutter bridge for KMP Shared SDK
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.nadeem.project.flutter_bridge
        pluginClass: KmpSharedSdkFlutterPlugin
      ios:
        pluginClass: KmpSharedSdkFlutterPlugin